### ISSUE TITLE
Exception when running tests after updating to version NUnit.Engine 3.16.2

### ISSUE THREAD

**Issue by danielmertens** [nunit/nunit3-vs-adapter#1051]
NUnit version: 3.13.3
NUnit3TestAdapter version: 4.3.1
NUnit.Engine version: 3.16.2
Nunit.Console version: 3.16.2
VS2022 version: 17.4.3
TargetFramework: net 4.8

We are running into an issue in our specflow project. I am unable to run any tests from the visual studio test explorer or commandline after updating my nuget packages to version 3.16.2.

The following exception is thrown when running tests via the `dotnet test` command:

```
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load file or assembly 'nunit.engine, Version=3.15.2.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
Stack trace:
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Initialize()
   at NUnit.VisualStudio.TestAdapter.NUnitTestAdapter.Initialize(IDiscoveryContext context, IMessageLogger messageLogger) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitTestAdapter.cs:line 141
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 102
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass46_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

There is no other reference to nunit.engine 3.15.2.0 so I have no clue why it's trying to load that version. 
Do you have any idea of how to solve this issue?

**Comment by OsirisTerje** [comment]
The adapter 4.3.1 is based on Engine 3.15.2.  
We're currently working on version 4.4 with support for engine version 3.16.3, but there are still unresolved issues with it.
But, what is the reason for needing NUnit.Console and Engine separately?  You can run dotnet test as commandline tool instead, which then uses the adapter.

**Comment by danielmertens** [comment]
That would explain why it doesn't work. Then I'll have to wait for version 4.4. I'm trying to solve an issue where we get a message about .NET 7 not being a known framework when running the tests.

There doesn't seem to be a reason why the console and engine packages were included in the project. Everything seems to run fine after removing them from the solution. I've inherited this codebase so I'm not certain what the original reason was for including them in the solution. Though I've also had to remove some NUnit v2 packages from the solution so it may have been something that didn't get deleted when migrating or someone added it by mistake.

**Comment by OsirisTerje** [comment]
The issue of Net 7 should work in 4.3.1 with it's built-in engine 3.15.2.

I know there are some earlier documents stating you needed COnsole and Engine packages.  It may be a result of that information, but in recent versions they are no longer needed as explicit packages.

**Comment by danielmertens** [comment]
You were completely correct that it works with 4.3.1. I dug deeper in our code and found that a CI script was directly downloading the ConsoleRunner 3.14.0 and using that version to run the tests. After I changed that to 3.15.2 it works perfectly. 

So it was definitely an us problem. Thanks for responding so quickly!
