### ISSUE TITLE
Unknown framework version 7.0

### ISSUE THREAD

**Issue by JPSm2023** [nunit/nunit3-vs-adapter#1090]
Hi 

I'm currently using the source code to integrate Playwright dotnet into Testrail

Every time I run:
./NuGet/nunit.consolerunner/3.15.0/tools/nunit3-console SimpleTestProject/bin/Debug/net6.0/SimpleTestProject.dll --trace off --result "reports/junit-report.xml;transform=SimpleTestProject/nunit3-junit.xslt"

I get the following:

NUnit Console 3.15.0 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
28 April 2023 09:41:46

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    SimpleTestProject/bin/Debug/net6.0/SimpleTestProject.dll

System.TypeInitializationException : The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception.
  ----> System.ArgumentException : Unknown framework version 7.0
Parameter name: version

--TypeInitializationException
The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception.
   at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.GetEngineRunner()
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
--
ArgumentException
Unknown framework version 7.0
Parameter name: version
   at NUnit.Engine.RuntimeFramework.GetClrVersionForFramework(Version frameworkVersion)
   at NUnit.Engine.RuntimeFramework..ctor(RuntimeType runtime, Version version, String profile)
   at NUnit.Engine.RuntimeFramework.GetNetCoreRuntimesFromDirectoryNames(IEnumerable`1 dirNames)
   at NUnit.Engine.RuntimeFramework.FindDotNetCoreFrameworks()
   at NUnit.Engine.RuntimeFramework.get_AvailableFrameworks()
   at NUnit.Engine.Services.RuntimeFrameworkService..cctor()

If anyone has any ideas why this is happening your help would be greatly appreciated:
I have gone through the thread and changed versions  of NUnit3Testadaptor and this also did not work.

NUnit Version 3.13.3
NUnit3TestAdapter Version 4.4.2
Vscode Version 1.76.2
V Studio Version 17.5.2

**Comment by OsirisTerje** [comment]
Except that will crash with the adapter, which uses a non-released version of the engine, 3.15.4.  I am working on getting that out.   3.16.0 is broken on loading certain assemblies

**Comment by manfred-brands** [comment]
But if they use nunit-console, they don't need the adapter or they can use `dotnet test` instead of the nunit-console.
