### ISSUE TITLE
Exception when using test filters from .runsettings or --filter argument from dotnet test

### ISSUE THREAD

**Issue by thomasbiel** [nunit/nunit3-vs-adapter#1146]
NUnit 4.0.1
NUnit3TestAdapter  4.5.0
dotnet 6.0 / windows 11
running tests from command line via "dotnet test"

when using a test filter like
`(TestCategory != UsesNetwork) &amp; (TestCategory != LongRunning)`
in .runsettings file or via --filter argument for dotnet this exception occurs in some combination with name of the test/parameter value:

Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in [...].dll
An exception occurred in the driver while counting test cases.
   at NUnit.Engine.Runners.DirectTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Run(ITestEventListener listener, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 108
   at NUnit.VisualStudio.TestAdapter.Execution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 51
   at NUnit.VisualStudio.TestAdapter.VsTestExecution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 154
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 295
InnerException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index was out or range of valida values (Parameter 'index')
Actual value was 0.
   at NUnit.Framework.Interfaces.TNode.NodeList.ThrowArgumentOutOfRangeException(Int32 index)
   at NUnit.Framework.Interfaces.TNode.get_FirstChild()
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.GetChildNodeFilters(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(String xmlText)
   at NUnit.Framework.Api.FrameworkController.CountTests(String filter)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(MethodInfo method, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(String methodName, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.CountTestCases(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.CountTestCases(TestFilter filter)

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by thomasbiel** [comment]
I got the filter mixed up, I started with `--filter TestCategory!=CategoryA&TestCategory!=CategoryB` but that didn't work, so I read the documentation and tried the NUnit-specific version `-- NUnit.Where="cat != CategoryA and cat != CategoryB"`, also w/o luck - regardless of adding the filter via CLI or in .runsettings

**Comment by thomasbiel** [comment]
Gotcha - everything works fine until there is a test marked with [Explicit] along with non-marked tests in a fixture.
[NUnitFilterSample.zip](https://github.com/nunit/nunit3-vs-adapter/files/13672795/NUnitFilterSample.zip)

**Comment by OsirisTerje** [comment]
What happens when there is an Explicit there?

**Comment by thomasbiel** [comment]
Then you get the mentioned exception, otherwise the testrun completes

**Comment by OsirisTerje** [comment]
Thanks @thomasbiel .  I can repro this.  I made the sample you added a bit simpler, and it seems that it crashes with only the single test class with 2 tests, one explicit, and one not.  

Also, it crashes when the filter has two categories, but not with only one.
And the Explicit triggers it, remove that and it works.

I added dump files, and the filter line that is sent to the framework is:

```xml
<filter><and><not><cat>Sample</cat></not><not><cat>Stress</cat></not></and><not><prop name='Explicit'>true</prop></not></filter>
```

I have added two cmd files, one `crash.cmd` and one `works.cmd`.

The stack trace indicates the crash happens in the framework, so I will move this issue there.

The repro can be found here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1146/NUnitFilterSample/src
