### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by ilyubin** [nunit/nunit3-vs-adapter#168]
I've run test from powershell with command like:
```
nunit3-console .\MyCompany.IntegrationTest.dll `
  --where:cat!=ExtractData `
  --result "TestResult.xml;format=nunit2"
```
It starts with:
```
NUnit Console Runner 3.2.1 
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    .\MyCompany.IntegrationTest.dll

Test Filters
    Where: cat!=ExtractData
```
5 test passed, then exception arised:
```
Errors and Failures

1) Error : 
Exception has been thrown by the target of an invocation.

Server stack trace: 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-05-13 12:04:30Z
    End time: 2016-05-13 12:15:51Z
    Duration: 681.056 seconds
```
Nunit 3.2.1 version

What to do?

**Comment by CharliePoole** [comment]
Looks like a problem using process runner. Would you try running with --

**Comment by CharliePoole** [comment]
BTW this doesn't seem to have anything to do with the VS adapter.

**Comment by ilyubin** [comment]
It return: Invalid argument: --improves
And I ran not from VS, from command lne powershell with nunit3-console.exe

**Comment by ChrisMaddock** [comment]
I'd imagine that was a typo, and @CharliePoole meant the `--inprocess` option. :-)

**Comment by CharliePoole** [comment]
@ChrisMaddock Yes... thank auto-correct. I fixed the comment.
@ilyubin I mentioned VS because you filed this as a VS adapter issue. It's actually an NUnit issue.

**Comment by ilyubin** [comment]
Sorry, I put it issue in wrong place. I hope it not big problem.

**Comment by CharliePoole** [comment]
Not a problem... just explaining my comment.

**Comment by rameshnss** [comment]
Is this issue fixed?  if not any workaround for this issue?

**Comment by CharliePoole** [comment]
Waiting to hear back from the person who created it about whether use of --inprocess helps. Until we know what causes the problem, we can't do much.

Since the only info we have is a very general exception, it really is not possible to judge if you are having the same problem as this one.

**Comment by rameshnss** [comment]
When I try to include --inprocess, I'm getting this error "Cannot run tests in process - a 32 bit process is required."  I tried to change the Default Processor architecture( X86 and X64) in my visual studio but still same error. 
but when I had successful run I noticed that Processor using is X86 only that displayed in nunit3 console results commandline..

**Comment by harrymitchinson** [comment]
I have also been getting this issue, seems to be happening randomly, have tried --inprocess and I get the same error as @rameshnss. I have about 25 testcases in and it seems to happen towards the end of the run. Console just shows the starting driver messages rather than my running log which I have added for each test case. Then at the end of all the test cases it shows the same exception as @ilyubin in his first post including the 0 passed, failed, etc. 

I will try get some logs tomorrow?

**Comment by CharliePoole** [comment]
I'm closing the issue because it's causing a lot of confusion - at least to me. Obviously, there is no way you can be using the --inprocess option with the NUnit 3 VS Adapter. I created a new issue for NUnit itself (#1548) that deals with this.

**Comment by CharliePoole** [comment]
Any further info should go to the new issue under NUnit: #1548.

If you are running under the VS adapter or a CI system that may invoke NUnit in it's own odd way, we already understand why this happens.

If you find this error occurs when __directly__ running the nunit3 console, that's new and we could use with more details.

**Comment by sergeyfsv** [comment]
Have you managed to solve this issue? I have the same problem of running nunit3 console in Bamboo (CI) and it fails with the same error.

**Comment by jnm2** [comment]
@sergeyfsv Which version of the NUnit VS adapter? https://github.com/nunit/nunit/issues/1548 was fixed in 3.4 and we're up to 3.7 now.

**Comment by jnm2** [comment]
My bad, which version of the NUnit _framework_?

**Comment by sergeyfsv** [comment]
We use 3.2.6. Seems have to upgrade it to the latest version. BTW, --inprocess helped a lot.

**Comment by jnm2** [comment]
:+1: A lot of cool improvements have happened since 3.2 like being able to turn on test case parallelization.
