### ISSUE TITLE
Visual Studio Test Adapter - Writing to test output throws an error

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#220]
@Slimfit commented on [Fri Aug 19 2016](https://github.com/nunit/docs/issues/106)

I am using NUnit nuget package 3.4.1 with NUnit 3 Test adapter 3.4.1. 
The following test:

```
[Test]
public void Test()
{
    Debug.WriteLine("DEBUG");
    Console.WriteLine("CONSOLE");
    Trace.WriteLine("TRACE");
 }
```

will output this in the "Show output from Tests" window:

> ------ Discover test started ------
NUnit Adapter 3.4.1.0: Test discovery starting
NUnit Adapter 3.4.1.0: Test discovery complete
========== Discover test finished: 5 found (0:00:00.2279294) ==========
------ Run test started ------
NUnit Adapter 3.4.1.0: Test execution started
Running selected tests in C:\Code\mydll.dll
NUnit3TestExecutor converted 5 of 5 NUnit test cases
D
E
B
U
G
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
T
R
A
C
E
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
NUnit Adapter 3.4.1.0: Test execution complete
========== Run test finished: 1 run (0:00:12.6423955) ==========

---

@CharliePoole commented on [Fri Aug 19 2016](https://github.com/nunit/docs/issues/106#issuecomment-241180046)

It's an interesting problem. NUnit actually does nothing special for Debug and Trace output, so I'm not clear how the TestOutput event handler is activated.

Since you say you are using the NUnit 3 Adapter, I'm moving this issue to that repository. This is the repository for NUnit documentation.

**Comment by jasonholloway** [comment]
I suddenly had this happening on my machine (after updating a big swathe of frameworky nugets) with exactly the same set up as @Slimfit above.

But - after downgrading the NUnit library to 3.2.1, without touching the adaptor, all is once again fine.

**Comment by CharliePoole** [comment]
@jasonholloway Thanks for confirming this.

**Comment by flouk19** [comment]
I still have this error, I am on the current version(from NuGet --> 3.5)
I try to write something to the output with `Debug.WriteLine(..)` and it is looking like @Slimfit 's result in the output window (for every letter a new Line and an Error after every print
`Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parametername: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)`

Best Regards Flo

**Comment by CharliePoole** [comment]
@flouk19 The extra line per write is caused by the VS logger itself, which creates a new line each time we write to the log. Is it only with `Debug.WriteLine()` that you see the problem - as opposed to `Console`?
