### ISSUE TITLE
No explanation of aborting test when a static constructor throws exception.

### ISSUE THREAD

**Issue by ngbrown** [nunit/nunit3-vs-adapter#334]
I was finally able to track down the issue by debugging a single tests in Visual Studio, but I would expect more output when the test assembly throws exceptions of any sort.

This is a .netcoreapp (2.0.0-preview1-005977), with Visual Studio 2017.3.  I've tried using both the command line `dotnet test` and the NuGet adapter in Visual Studio.

```
PS C:\dev\OSS\nhibernate-core\src\NHibernate.Test> dotnet test
Build started, please wait...
Build completed.

Test run for C:\dev\OSS\nhibernate-core\src\NHibernate.Test\bin\Debug\netcoreapp2.0\NHibernate.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\dev\OSS\nhibernate-core\src\NHibernate.Test\bin\Debug\netcoreapp2.0\NHibernate.Test.dll
NUnit3TestExecutor converted 5694 of 5694 NUnit test cases
The active test run was aborted. Reason:

PS C:\dev\OSS\nhibernate-core\src\NHibernate.Test>
```

This is what I get at the command prompt (`dotnet test -v detailed`), after all the build noise:

```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\dev\OSS\nhibernate-core\src\NHibernate.Test\bin\Debug\netcoreapp2.0\NHibernate.Test.dll
NUnit3TestExecutor converted 5694 of 5694 NUnit test cases
The active test run was aborted. Reason:

       Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestTask" -- FAILED.
     1>Done building target "VSTest" in project "NHibernate.Test.csproj" -- FAILED.
     1>Done Building Project "C:\dev\OSS\nhibernate-core\src\NHibernate.Test\NHibernate.Test.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:43.47
```

**Comment by rprouse** [comment]
Can you provide more context as to what sort of static constructor caused the entire test process to crash?

I tried a simple tests,

```C#
[TestFixture]
public class StaticConstructorTests
{
    static class ClassWithStaticConstructor
    {
        static ClassWithStaticConstructor()
        {
            throw new Exception("Crash!");
        }

        public static int Add(int x, int y) => x + y;
    }

    [Test]
    public void UseClassWithStaticConstructor()
    {
        Assert.That(ClassWithStaticConstructor.Add(2, 2), Is.EqualTo(4));
    }
}
```

And I get the following at the command line,

```
Test run for C:\src\nunit\NUnitPlatformTests\test\NetCore10Tests\bin\Debug\netcoreapp1.0\NetCore10Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\src\nunit\NUnitPlatformTests\test\NetCore10Tests\bin\Debug\netcoreapp1.0\NetCore10Tests.dll
NUnit3TestExecutor converted 16 of 16 NUnit test cases
Failed   UseClassWithStaticConstructor
Error Message:
 System.TypeInitializationException : The type initializer for 'ClassWithStaticConstructor' threw an exception.
  ----> System.Exception : Crash!
Stack Trace:
   at NetCore10Tests.StaticConstructorTests.ClassWithStaticConstructor.Add(Int32 x, Int32 y) in C:\src\nunit\NUnitPlatformTests\test\NetCore10Tests\StaticConstructorTests.cs:line 18
   at NetCore10Tests.StaticConstructorTests.UseClassWithStaticConstructor() in C:\src\nunit\NUnitPlatformTests\test\NetCore10Tests\StaticConstructorTests.cs:line 24
--Exception
   at NetCore10Tests.StaticConstructorTests.ClassWithStaticConstructor..cctor() in C:\src\nunit\NUnitPlatformTests\test\NetCore10Tests\StaticConstructorTests.cs:line 15
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 16. Passed: 15. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.6848 Seconds
```

And in Visual Studio I get

![image](https://cloud.githubusercontent.com/assets/493828/26583561/c13a537e-4513-11e7-9eba-7f449816fb6b.png)

Is your static constructor getting called outside of your tests, for example in a `TestCaseSource`?

**Comment by OsirisTerje** [comment]
No response in 28 days, so assume this is ok.
