### ISSUE TITLE
Remapping CurrentDirectory

### ISSUE THREAD

**Issue by brantkev** [nunit/nunit3-vs-adapter#362]
Have recently updated to Nunit3 Adapter (3.7.0)  When executing tests within Visual Studio 2015, we are seeing the CurrentDirectory now mapped to _C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE_ .

Within the test code, we use a the following line to get test assets that are in the working directory for the test code using **Directory.GetCurrentDirectory()**.  Based on the method documentation, this is to return the working directory.  Under Nunit2, this returned the correct path _C:\Projects\ena\UAT\IntegrationTests\_, which is the test project path.

Downgrading to Nunit2, confirmed this is working as expected, but when Nunit3 is applied the incorrect directory is returned by the method.

**Error Stack Trace**
Result StackTrace:	
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at IntegrationTests.Features.Offer.PromotionTemplateFeature..ctor(String jsonSample) in C:\Projects\ena\UAT\IntegrationTests\Features\Offer\PromotionTemplateFeature.cs:line 43
   at IntegrationTests.Steps.Offer.PromotionTemplateSteps.GivenAsAOCEUserIWantToUseTemplate(PromotionTemplateEnum promotionTemplate) in C:\Projects\ena\UAT\IntegrationTests\Steps\Offer\PromotionTemplateSteps.cs:line 31
   at lambda_method(Closure , IContextManager , PromotionTemplateEnum )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at IntegrationTests.Scenarios.Customer.OfferTypeConfigurableFeature.ScenarioCleanup()
   at IntegrationTests.Scenarios.Customer.OfferTypeConfigurableFeature.CheckinUsingPromotionTemplate27WhereProductQuantityEqualsMinQuantityAndIsGreaterThanMinQuantity(String title, String promotionTemplate, String shortDscr, String longDscr, String offerType, String exclusive, String quantity, String allowedQty, String priority, String storeID, String productSetName, String total, String tax, String[] exampleTags) in C:\Projects\ena\UAT\IntegrationTests\Scenarios\Customer\OfferTypeConfigurable.feature:line 155
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Json\PromotionTemplates\PriceDeal.json'.

**Comment by CharliePoole** [comment]
This is a change in the NUnit 3 framework and is not related to the adapter at all.

NUnit 2 actually changed the current directory in order to guarantee that it was set to the directory containing the test assembly. This was convenient but questionable, since programs that change the current directory can lead to surprises.

With NUnit 3 and parallel execution of assemblies it became unsustainable. NUnit no longer changes the current directory.

You may use TextContext.TestDirectory to find the location of the current test assembly.
