### ISSUE TITLE
Linux test runs abort with no reason given

### ISSUE THREAD

**Issue by chlowell** [nunit/nunit3-vs-adapter#377]
I'm running a `netcoreapp2.0` test project with NUnit3 3.7.1 and NUnit3TestAdapter 3.8.0. On Windows, test runs complete as expected:
```console
$ dotnet test
...
NUnit3TestExecutor converted 169 of 169 NUnit test cases
...
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 169. Passed: 164. Failed: 0. Skipped: 5.
Test Run Successful.
```

On Linux, test runs very rarely complete. Typically they abort with no reason given after 46 or 55 tests:
```console
$ dotnet test
...
NUnit3TestExecutor converted 169 of 169 NUnit test cases
...
The active test run was aborted. Reason:

Total tests: 55. Passed: 49. Failed: 1. Skipped: 5.
Test Run Failed.
```
(the failed test is expected, and test runs abort when it's skipped)

I built a repro image for more convenient debugging:
> `docker run chlowe/nunit3-linux-repro`

Here's my csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
    <AssemblyName>log4net.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Appender\DebugAppenderTest.cs;Appender\EventLogAppenderTest.cs;Appender\RemotingAppenderTest.cs;Util\PatternStringTest.cs" />
    <ProjectReference Include="..\..\src\log4net.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>
</Project>
```

**Comment by OsirisTerje** [comment]
@CharliePoole Do you have linux installed to verify this?  I am at a loss here.

**Comment by chlowell** [comment]
If the image isn't convenient, you can repro it manually (Bash on Windows is sufficient):
```console
git clone https://github.com/chlowell/logging-log4net.git --single-branch --branch netstandard2 --depth 1 log4net
dotnet test log4net/tests/src/log4net.Tests.csproj
```

**Comment by bernardbr** [comment]
I installed a fresh instance of ubuntu 16.04 with netcore 2.0 and ran the test command.
This is the output:

```
Build started, please wait...
Build completed.

Test run for /home/dsnerp/Projetos/log4net/tests/src/bin/Debug/netcoreapp2.0/log4net.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in /home/dsnerp/Projetos/log4net/tests/src/bin/Debug/netcoreapp2.0/log4net.Tests.dll
NUnit3TestExecutor converted 169 of 169 NUnit test cases
Failed   TestExclusiveLockLocks
Error Message:
   Log contents is not what is expected
  String lengths are both 38. Strings differ at index 0.
  Expected: "This is a message\nThis is a message 2\n"
  But was:  "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0This is a message 2\n"
  -----------^

Stack Trace:
at log4net.Tests.Appender.RollingFileAppenderTest.AssertFileEquals(String filename, String contents) in /home/dsnerp/Projetos/log4net/tests/src/Appender/RollingFileAppenderTest.cs:line 1519
at log4net.Tests.Appender.RollingFileAppenderTest.TestExclusiveLockLocks() in /home/dsnerp/Projetos/log4net/tests/src/Appender/RollingFileAppenderTest.cs:line 1619

Skipped  TestInitialization3
Error Message:
 Not Implemented: Want to test counted files limited up, to see that others are ?? ignored? deleted?

Skipped  TestInitialization4
Error Message:
 Not Implemented: Want to test counted files limited down, to see that others are ?? ignored? deleted?

Skipped  TestInitialization5
Error Message:
 Not Implemented: Want to test dated files with a limit, to see that others are ?? ignored? deleted?

Skipped  TestInitialization6
Error Message:
 Not Implemented: Want to test dated files with no limit, to see that others are ?? ignored? deleted?

Skipped  TestInitialization7
Error Message:
 Not Implemented: Want to test dated files with mixed dates existing, to see that other dates do not matter


Total tests: 54. Passed: 48. Failed: 1. Skipped: 5.
Test execution time: 13.0455 Seconds
```

**Comment by chlowell** [comment]
Interesting you didn't get the "test run aborted message" considering the run didn't complete.

I see a more informative message doing the same thing targeting `netcoreapp1.0` (running on Debian Jessie):
```console
λ docker run --rm chlowe/nunit3-linux-repro:netcoreapp1.0
Test run for /log4net/tests/src/bin/Debug/netcoreapp1.0/log4net.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in /log4net/tests/src/bin/Debug/netcoreapp1.0/log4net.Tests.dll
NUnit3TestExecutor converted 160 of 160 NUnit test cases
...
The active test run was aborted. Reason: Unable to communicate with test host process.
```
... and then it appears to hang.

Here's the Dockerfile for that image, in case you want to follow along elsewhere:
```Dockerfile
FROM microsoft/dotnet:1.1.2-sdk-jessie
RUN git clone https://github.com/chlowell/logging-log4net.git \
    --single-branch --branch netstandard-testing --depth 1 log4net
WORKDIR /log4net/tests/src
RUN dotnet restore
RUN dotnet build -f netcoreapp1.0
CMD dotnet test -f netcoreapp1.0 --no-build
```

**Comment by AnthonyMastrean** [comment]
I have this same error on _some_ of my project test runs. Trying to compare two projects now to see if there are any significant differences. Will update...

**Comment by chlowell** [comment]
In my project's case, test runs abort because the test executor process segfaults. I haven't narrowed down the cause of the segfault (looks like it originates in application code) or figured out why it only occurs on Linux, but I don't see anything implicating nunit. I'll close this issue now, and reopen if appropriate.

@AnthonyMastrean for debugging your own project, you can start with the `--blame` flag for the test host, available in prerelease versions of the SDK, which will tell you which test is executing when the run fails; see https://github.com/Microsoft/vstest/issues/1069#issuecomment-350048544. If you're dealing with a failure which doesn't throw a managed exception, you'll want a dump. Here's a [blog post](http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/) to get you started there.
