### ISSUE TITLE
DateTime.Parse issue during test discovery with certain cultures

### ISSUE THREAD

**Issue by NightOwl888** [nunit/nunit3-vs-adapter#386]
We are using randomized cultures when testing and are occasionally finding these errors in the log:

```
Error processing test-case event for Lucene.Net.Search.Suggest.Analyzing.FuzzySuggesterTest.TestEditSeps
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 195
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestResultFromLegacyXmlNode(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 160
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVSTestResults(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 113
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 146
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 83
Error processing test-case event for Lucene.Net.Search.Suggest.Analyzing.FuzzySuggesterTest.TestEmpty
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 195
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestResultFromLegacyXmlNode(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 160
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVSTestResults(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 113
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 146
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 83
Error processing test-case event for Lucene.Net.Search.Suggest.Analyzing.FuzzySuggesterTest.TestExactFirst
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 195
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestResultFromLegacyXmlNode(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 160
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVSTestResults(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 113
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 146
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 83
Error processing test-case event for Lucene.Net.Search.Suggest.Analyzing.FuzzySuggesterTest.TestGraphDups
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 195
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestResultFromLegacyXmlNode(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 160
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVSTestResults(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\TestConverter.cs:line 113
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 146
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in C:\Users\terje_000\Source\Repos\nunit\nunit3testadaper\src\NUnitTestAdapter\NUnitEventListener.cs:line 83
```
The result of these exceptions is that certain tests are not added to the test fixture.

I didn't have the specific culture the test was run under when this happened because it wasn't in the log, but it is pretty clear that you are calling the overload that doesn't pass in a culture instead of calling the one that does and passing in `CultureInfo.InvariantCulture` in order to reliably parse the date across all ambient cultures.

I am using

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
    <!-- Required by NUnit3TestAdapter on .NET Core -->
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="TeamCity.VSTest.TestAdapter" Version="1.0.3" />
```

Let me know if you need more info than this.

Do note we also get warnings if `System.Runtime.InteropServices.RuntimeInformation` is not referenced. It seems like this is something you should do so we don't get these warnings as consumers.

**Comment by OsirisTerje** [comment]
Thanks for pointing this out!  Seems pretty obvious.

**Comment by NightOwl888** [comment]
> Runtimeinformation: I haven't seen this. Do you have an example?

I tried commenting them out, but I can't seem to reproduce the warning anymore. I believe that I saw it happening when I was referencing NUnit 3.7.1 and Microsoft.NET.Test.Sdk 15.0.0, but I don't recall if it happened during build or test discovery.
