### ISSUE TITLE
Fatal NUnit crash when running one specific test on .NET Core 2.0

### ISSUE THREAD

**Issue by NightOwl888** [nunit/nunit3-vs-adapter#387]
## Problem

This is one of the issues that came out of #381. We are getting a fatal crash *only* when running one specific test on .NET Core 2.0. It doesn't happen on .NET Core 1.0 or .NET Framework 4.5.1, and it only happens around 1/3 of the time. The stack trace is:

```
[9/14/2017 3:24:20 PM Informational] NUnit3TestExecutor converted 3504 of 3504 NUnit test cases
[9/14/2017 3:24:47 PM Error] The active test run was aborted. Reason: ystem.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[])
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Run(NUnit.Framework.Interfaces.ITestListener, NUnit.Framework.Interfaces.ITestFilter)
   at NUnit.Framework.Api.FrameworkController.RunTests(System.Action`1<System.String>, System.String)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(System.Reflection.MethodInfo, System.Object[])
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.Run(NUnit.Engine.ITestEventListener, System.String)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(NUnit.Engine.ITestEventListener, NUnit.Engine.TestFilter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(NUnit.Engine.ITestEventListener, NUnit.Engine.TestFilter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(NUnit.Engine.ITestEventListener, NUnit.Engine.TestFilter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(System.String, NUnit.Engine.TestFilter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase>, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(System.Collections.Generic.IEnumerable`1<System.Tuple`2<System.Uri,System.String>>, Int64)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestsInternal()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTests()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.ExecutionManager.StartTestRun(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase>, System.String, Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ClientProtocol.TestExecutionContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ITestCaseEventsHandler, Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunEventsHandler)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler+<>c__DisplayClass10_5.<ProcessRequests>b__6()
   at Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SafeProcessJob(System.__Canon)
   at Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].BackgroundJobProcessor()
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[9/14/2017 3:24:47 PM Informational] ========== Run test finished: 0 run (0:00:51.5149383) ==========
```

The stack trace indicates it is crashing *before* it even reaches my code. It would be extremely helpful if you would have a look to see why this crash happens.

Since this is such an oddity, I doubt I would be able to reliably reproduce it outside of our project. So, I am afraid the only way is to clone [our repository](https://github.com/apache/lucenenet/tree/6a95ad434d422cf1ed2b746e2cbf5d0de633b442) and fire up this test in Visual Studio 2017. [Here is the test](https://github.com/apache/lucenenet/blob/6a95ad434d422cf1ed2b746e2cbf5d0de633b442/src/Lucene.Net.Tests/Index/TestTermVectorsFormat.cs#L84-L92) that is crashing. Of course, you will need to comment out the manual test failure that we have put in place to keep the test runner alive.

Note that I have looked at the test and tried to use `ToList()` on the `IEnumerable<T>` that is being looped through. Although it seemed to make the test fail less frequently, it didn't solve the problem completely.

**Comment by rprouse** [comment]
That is pretty crazy, it looks like the execution of the test method via reflection is failing. I will leave this issue here for now, but it looks like a framework issue, not an adapter issue, we are well down into the NUnit framework code when it fails. I looked at your tests and I don't see anything different about it.

Would it be possible to create a .NET Core 2.0 console app that executes that test directly? I am curious if it is a poorly reported error in .NET Core that your test is exposing and we are not handling well. It is also a bit odd that the first part of the call stack looks cut off.

**Comment by NightOwl888** [comment]
I ran from a console app like you suggested and the test runs fine all the way through, so there is no error to report :(.

```c#
            var test = new Lucene.Net.Index.TestTermVectorsFormat();

            try
            {
                test.BeforeClass();
                test.SetUp();

                test.TestLotsOfFields();

                test.TearDown();
                test.AfterClass();
            }
            catch (Exception ex)
            {

            }
```

It is really bizarre that it fails here, but the same exact test with some different components plugged in works fine in other similar subclasses.

The call stack was cut off when I reported [this bug](https://github.com/Microsoft/vstest/issues/1022) as well. We are also seeing tests that "can't possibly fail" fail on .NET Core 2.0, but only on the command line where we can't debug them...

**Comment by NightOwl888** [comment]
Hmm...

After I mentioned that other subclasses with the same test were succeeding, I thought "what is different about this class?" So, I changed the class name and now it works without crashing. And I changed it back and it still works without crashing. Apparently, this is some problem with the compiler optimization and/or my CPU is melting down (hopefully not the latter).

**Comment by rprouse** [comment]
@NightOwl888 sounds like a .NET Core bug to me. Not really surprising since it is still so new. I am going to close this as we will not have the time to track the bug down ourselves. If you feel it should remain open, let me know.
