### ISSUE TITLE
Random failing of parallel test run: Unhandled Exception: System.InvalidOperationException: Stack empty.

### ISSUE THREAD

**Issue by YRudievGP** [nunit/nunit3-vs-adapter#491]
Sorry if dublicate, I didn't find the issue.

Random failing of parallel test run. 
More then one hundred tests are in the test run and they are running parallel ([Parallelizable(ParallelScope.Fixtures)]). 
Seems that different threads trying to take next test when they are finished (it occurs in the end of the run).

Call stack:
The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: Stack empty.
[11:25:57][test]    at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
[11:25:57][test]    at System.Collections.Generic.Stack`1.Pop()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.WorkItemQueue.Restore()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.RestoreQueues()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.OnEndOfShift(WorkShift endingShift)
[11:25:57][test]    at NUnit.Framework.Internal.Execution.WorkShift.<StartWorkers>b__26_1(TestWorker s, WorkItem ea)
[11:25:57][test]    at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
[11:25:57][test]    at System.Threading.Thread.ThreadMain_ThreadStart()
[11:25:57][test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

NUnit: 3.10.1
NUnit3testAdapter: 3.10.0
Target framework: netcoreapp2.0
CI: TeamCity 2017.2.1 (build 50732)
OS: Linux Ubuntu

**Comment by rprouse** [comment]
This issue was moved to nunit/nunit#2772
