### ISSUE TITLE
Nunit test runner fails to find or run tests in visual studio 2017

### ISSUE THREAD

**Issue by sereeth** [nunit/nunit3-vs-adapter#496]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
Nunit 3.10.0

* Visual Studio edition and full version number (see Help About)
15.6.1

* What .net platform and version is being targeted
<TargetFrameworks>netstandard2.0;net471;netcoreapp2.0</TargetFrameworks>

```
[2018-03-28 4:25:52 PM Warning] An exception occurred in the driver while loading tests.
[2018-03-28 4:25:52 PM Warning]    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
[2018-03-28 4:25:52 PM Warning] Innerexception: System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
File name: 'nunit.framework'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
```

csproj looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net471;netcoreapp2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.6.2" />
    <PackageReference Include="DataGenerator" Version="4.0.0.19" />
    <PackageReference Include="FluentAssertions" Version="5.1.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.1" />
    <PackageReference Include="NBuilder" Version="5.0.0" />
    <PackageReference Include="NUnit" Version="3.10.1" />
    <PackageReference Include="ServiceStack" Version="5.0.3" />
    <PackageReference Include="ServiceStack.OrmLite" Version="5.0.3" />
    <PackageReference Include="ServiceStack.OrmLite.Sqlite" Version="5.0.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.4.1" />
  </ItemGroup>
    <ItemGroup>
    <PackageReference Update="NETStandard.Library" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

**Comment by rprouse** [comment]
I see a few problems in your `csproj`,

1. Your tests cannot target `netstandard2.0`, they must target a specific framework. Drop that. See https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard#why-cant-my-tests-target-net-standard
2. You aren't referencing the NUnit adapter as a NuGet package. Visual Studio does not support VSIX based adapters for .NET Core test projects, you must use the NuGet version.
3. Be aware that multi-targeting tests is buggy in Visual Studio. It will only run one target, probably the first, which in your case is unsupported. You can run specific targets from the command line using `dotnet test`, but you need to use the NuGet adapter.

I am marking this as a question and closing. Comment if you need more help, we will see it.

**Comment by sereeth** [comment]
Thanks.  Multi-targeting and visual studio is a bit of a mess.

**Comment by jnm2** [comment]
I talked to Andrew Hall at a conference this week. He says they hear this pain a lot and have to balance it with higher priorities, but he thinks they will be putting .NET Standard unit test projects somewhere in the tooling roadmap they are releasing next month! 🎉
