### ISSUE TITLE
Limit of number of tests?

### ISSUE THREAD

**Issue by JennyLucasADLC** [nunit/nunit3-vs-adapter#504]
Hi Guys,

I ran into something and I thought I would pass it on.
I am using Visual Studio 2017 Enterprise, with NUnit 3.10.1, Nunit3TestAdapter 3.10.0 and Selenium 3.11 on Chrome.
I am doing a lot of parallel tests, so I have the following pattern: One class has one test procedure, and either the fixture has multiple inputs or the procedure does.
The error I was seeing in VS is below...

[5/7/2018 1:48:15 PM Informational] ------ Load Playlist started ------
[5/7/2018 1:48:15 PM Informational] ========== Load Playlist finished (0:00:00.002) ==========
[5/7/2018 1:48:35 PM Informational] ------ Run test started ------
[5/7/2018 1:48:38 PM Informational] NUnit Adapter 3.10.0.21: Test execution started
[5/7/2018 1:48:38 PM Informational] Running all tests in C:\Playground\TestBase\bin\LocalChrome\TestBase.dll
[5/7/2018 1:49:49 PM Warning] Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests in C:\Playground\TestBase\bin\LocalChrome\TestBase.dll
[5/7/2018 1:49:49 PM Warning] An exception occurred in the driver while exploring tests.
[5/7/2018 1:49:49 PM Warning]    at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
[5/7/2018 1:49:49 PM Warning] Innerexception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
[5/7/2018 1:49:49 PM Informational] NUnit Adapter 3.10.0.21: Test execution complete
[5/7/2018 1:49:49 PM Warning] No test is available in C:\Playground\TestBase\bin\LocalChrome\TestBase.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[5/7/2018 1:49:50 PM Informational] ========== Run test finished: 0 run (0:01:14.8753349) ==========

I tried uninstalling, reinstalling, patching everything I could think of. No luck there.
I restored a backup of my entire project. No luck.
Tried changing .Net Framework versions 4.5.2 -> 4.6.2 and back again
But then, for some reason, I commented out a bunch of the test fixtures and all their procedures. VIOLA!
(To be clear, I saw the tests in the Visual Studio Text Explorer, and the above was output when I tried to RUN a test. Any test. On the other hand, when I tried to DEBUG a test, I literally got nothing in the output window.)

After commenting out, I noticed that the Visual Studio Output window reported that I had over 10,000 tests. So, I'm guessing there were over 20,000 at one point. YES, I agree that's a lot! 
Now, I am going through a big paradigm shift and changing the tests so I am not testing negative outcomes. That will significantly reduce the number of tests.

But I thought I would share. See, it's easy to have large numbers of combinations of input parameters. And tracking down this little bugger cost me a couple of days.

Jenny

**Comment by rprouse** [comment]
What happens if you run your tests on the command line using NUnit Console? Does it use as much memory? If it does, you could profile your tests to find out where the memory is being consumed.

If you don't want to delete all your tests, splitting them into multiple assemblies might help.

**Comment by JennyLucasADLC** [comment]
I didn't try the NUnit Console. I did use the Console Runner (but not sure if that should be considered as I don't know WHEN the problem started.)

I thought about multiple assemblies but I haven't tried that yet.

Here's what I will do. Time permitting, I will create a new project and load it up with fake tests... If I can replicate the issue, I will post the entire solution here for anyone to review. Give me a day or two.

**Comment by JennyLucasADLC** [comment]
OK, ok, I did it already. :)
I copied my entire solution and sanitized it. It will build, but not actually do anything. :)
I have removed packages and bin folders to keep the file size down.
[Playground-STRIPPED.zip](https://github.com/nunit/nunit3-vs-adapter/files/1984578/Playground-STRIPPED.zip)
Hope that helps!

**Comment by OsirisTerje** [comment]
@JennyLucasADLC  Hi!  Sorry for this having taken so much time.  Your memory issues are being catched by the adapter so all is working fine there.  Repro is working. 
However, I see your point about this being hard to discover.  We don't have that many options though.  We could mark the test as Inconclusive, since it has not run, but that would not make any difference on the Test Explorer view.  We could also require a test to not blow up, and thus mark it as failed, but that would be cheating - because you didn't state that fact in your test - we did it for you.  I still wonder if not  that would be better than the existing approach.
