### ISSUE TITLE
Can't run tests in a .net 3.5 project

### ISSUE THREAD

**Issue by FruitcakeElemental** [nunit/nunit3-vs-adapter#588]
Hi Guys,

I updated my Visual Studio (to 15.9.5) the other day then went to run a unit test from test explorer in a 3.5 project of mine and got this error message:

```
[23/01/2019 2:15:45 AM Informational] ------ Run test started ------
[23/01/2019 2:15:45 AM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Framework35 is not supported. For projects targeting .Net Framework 3.5, please use Framework40 to run tests in CLR 4.0 "compatibility mode".
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.UpdateRunSettingsIfRequired(String runsettingsXml, List`1 sources, String& updatedRunSettingsXml)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass19_0.<StartTestRun>b__0()
[23/01/2019 2:15:45 AM Informational] ========== Run test finished: 0 run (0:00:00.1069443) ==========
```

I am using the latest NUnit and NUnit3TestAdapter nuget packages.

Googling for answers I found [this](https://github.com/Microsoft/vstest/pull/1723), might be related?  I suspect this may be Microsoft's change, but the error message is really unhelpful, I've spent a while googling how to run tests in 4.0 compatibility without any success.

**Comment by rprouse** [comment]
I moved this issue to the adapter project so people can find it and am going to close it because it is a change in Visual Studio, not in Nunit.
