### ISSUE TITLE
NUnit3TestExecutor.MakeTestFilter does not create valid xml

### ISSUE THREAD

**Issue by appel1** [nunit/nunit3-vs-adapter#68]
If a test contains & in its name the VS test adapter creates invalid xml in NUnit3TestExecutor.MakeTestFilter. Currently it only escapes < and > but it needs to escape & as well. 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Invalid filter element: tests
Parameter name: xmlNode
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(String xmlText)
   at NUnit.Framework.Api.FrameworkController.CountTests(ICallbackEventHandler handler, String filter)
   at NUnit.Framework.Api.FrameworkController.CountTestsAction..ctor(FrameworkController controller, String filter, Object handler)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.CountTests(TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.CountTests(TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyName, IFrameworkHandle frameworkHandle) in nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 201
```

Perhaps the VS adapter could include the full stack trace when it logs unexpected errors. The current output isn't all that helpful. 

```
------ Run test started ------
NUnit Adapter 3.0.5.0 executing tests is started
Loading tests from <assembly path>
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in <assembly path>
NUnit Adapter 3.0.5.0 executing tests is finished
========== Run test finished: 0 run (0:01:13,4043089) ==========
```

**Comment by CharliePoole** [comment]
This is the second critical bug in MakeTestFilter! CTP-6 will be out shortly.

Regarding the display, we have shortened it in general because users were being confused by unnecessary information. I'll take a look to see how we could have identified this as an internal error bug requiring a full stack trace. If I can't find anything quick and easy to do, I'll make a separate issue.
