### ISSUE TITLE
NullReferenceException in ExtractTestFixture in v4.0.0-beta2

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#852]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
* Visual Studio edition and full version number (see Help About)
* A short repro, preferably attached or pointing to a git repo or gist
* What .net platform and version is being targeted
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in

I updated a test solution that I use to test issues in the NUnit project to the latest beta of the adapter. Test discovery passes, but running all tests gives the following error in the output window;

```
Running all tests in C:\Src\NUnit\nunit-tests\nunit-v3\bin\Debug\nunit-v3.dll
Exception System.NullReferenceException,    Exception thrown executing tests in C:\Src\NUnit\nunit-tests\nunit-v3\bin\Debug\nunit-v3.dll
Object reference not set to an instance of an object.
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractTestFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 240
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 217
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 228
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 228
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ConvertXml(NUnitResults discovery) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 182
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.Convert(NUnitResults discoveryResults, String assemblyPath) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 131
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 279
NUnit Adapter 4.0.0.0: Test execution complete
```

This is using;

- NUnit 3.13.2
- Microsoft.NET.Test.Sdk 16.9.4
- NUnit3TestAdapter v4.0.0-beta.2
- Visual Studio Enterprise 16.9.4
- Both projects are old style CSPROJ files and target .NET 4.5

Interestingly, tests in the smaller NUnitLite solution with the same dependencies pass.

**Comment by OsirisTerje** [comment]
Do you have the code?    There are certain strange possible constellations that are not supported, simply because I don't know if they are for real......

**Comment by rprouse** [comment]
Sorry, I thought I added a link. It is the `nunit-v3` project in this repo, https://github.com/rprouse/nunit-tests
