### ISSUE TITLE
Running code coverage with vstest.console.exe causes System.Security.VerificationException: Operation could destabilize the runtime

### ISSUE THREAD

**Issue by mlop3s** [nunit/nunit3-vs-adapter#857]
* NUnit 3.13.0
* NUnit Adapter 3.17.0.0
* Microsoft Visual Studio Enterprise 2019 Version 16.9.4
* This happens with all our .net assemblies
* .Net Target: 4.7.2
* It happens on our azure 2019 on-premise 
* Visual Studio Test Version 2.157.3
* DtaExecutionHost version 17.153.29006.1.
* vstest.console.exe Version 16.9.4
* Coverage Collection Tool Version 16.0.21158.215801 

This error has been around since 2018 i guess. Now and then we try to enable it, all the time we update something on the test pipeline with no success. I hope this will be fixed on version 4.0 as coverage is really important for us.

Disabling coverage fixes the problem, but this is not the point.
Adding [assembly: SecurityRules(SecurityRuleSet.Level1, SkipVerificationInFullTrust = true)]  also seems to solve the problem.

Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests
The NUnit 3 driver encountered an error while executing reflected code.
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 83
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 293
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 110
InnerException: System.Security.VerificationException: Operation could destabilize the runtime.
   at NUnit.Framework.Api.FrameworkController..ctor(String assemblyNameOrPath, String idPrefix, IDictionary settings) in D:\a\1\s\src\NUnitFramework\framework\Api\FrameworkController.cs:line 68

Thanks.
Marco

**Comment by mlop3s** [comment]
Hi, we've tried adding  [assembly: SecurityRules(SecurityRuleSet.Level1, SkipVerificationInFullTrust = true)] which was working in the past. It does not work anymore. Same error.
This is the automatically generated runsettings file:
``` xml
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CodeCoverage>
            <ModulePaths>
              <Include>
                <ModulePath>.*.dll$</ModulePath>
                <ModulePath>.*.exe$</ModulePath>
              </Include>
              <Exclude>
                <ModulePath>.*CPPUnitTestFramework.*</ModulePath>
              </Exclude>
            </ModulePaths>
            <Functions>
              <Exclude>
                <Function>^Fabrikam\\.UnitTest\\..*</Function>
                <Function>^std::.*</Function>
                <Function>^ATL::.*</Function>
                <Function>.*::__GetTestMethodInfo.*</Function>
                <Function>^Microsoft::VisualStudio::CppCodeCoverageFramework::.*</Function>
                <Function>^Microsoft::VisualStudio::CppUnitTestFramework::.*</Function>
              </Exclude>
            </Functions>
            <Attributes>
              <Exclude>
                <Attribute>^System\\.Diagnostics\\.DebuggerHiddenAttribute$</Attribute>
                <Attribute>^System\\.Diagnostics\\.DebuggerNonUserCodeAttribute$</Attribute>
                <Attribute>^System\\.Runtime\\.CompilerServices.CompilerGeneratedAttribute$</Attribute>
                <Attribute>^System\\.CodeDom\\.Compiler.GeneratedCodeAttribute$</Attribute>
                <Attribute>^System\\.Diagnostics\\.CodeAnalysis.ExcludeFromCodeCoverageAttribute$</Attribute>
              </Exclude>
            </Attributes>
            <Sources>
              <Exclude>
                <Source>.*\\atlmfc\\.*</Source>
                <Source>.*\\vctools\\.*</Source>
                <Source>.*\\public\\sdk\\.*</Source>
                <Source>.*\\microsoft sdks\\.*</Source>
                <Source>.*\\vc\\include\\.*</Source>
              </Exclude>
            </Sources>
            <CompanyNames>
              <Exclude>
                <CompanyName>.*microsoft.*</CompanyName>
              </Exclude>
            </CompanyNames>
            <PublicKeyTokens>
              <Exclude>
                <PublicKeyToken>^B77A5C561934E089$</PublicKeyToken>
                <PublicKeyToken>^B03F5F7F11D50A3A$</PublicKeyToken>
                <PublicKeyToken>^31BF3856AD364E35$</PublicKeyToken>
                <PublicKeyToken>^89845DCD8080CC91$</PublicKeyToken>
                <PublicKeyToken>^71E9BCE111E9429C$</PublicKeyToken>
                <PublicKeyToken>^8F50407C4E9E73B6$</PublicKeyToken>
                <PublicKeyToken>^E361AF139669C375$</PublicKeyToken>
              </Exclude>
            </PublicKeyTokens>
            <UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            <CollectFromChildProcesses>True</CollectFromChildProcesses>
            <CollectAspDotNet>False</CollectAspDotNet>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
      <DataCollector friendlyName="blame" enabled="True">
        <Configuration>
          <ResultsDirectory>D:\agent_02\_work\_temp\TR_d2a7a449-0fb5-4685-aab6-9f978939826d</ResultsDirectory>
          <CollectDump />
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <RunConfiguration>
    <BatchSize>1000</BatchSize>
    <ResultsDirectory>D:\agent_02\_work\_temp\TR_d2a7a449-0fb5-4685-aab6-9f978939826d</ResultsDirectory>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="blame" enabled="True" />
    </Loggers>
  </LoggerRunSettings>
</RunSettings>
```

**Comment by OsirisTerje** [comment]
The code coverage is working, not sure what you're referring to about 2018.   And not sure how you have set this up.  Can you upload the yml file for the build?  

A good setup to get code coverage working is the following yml snippets:

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--no-build --collect:"XPlat Code coverage"'

- script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8'  
  displayName: 'Install ReportGenerator tool' 

- script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'  
  displayName: 'Create reports'    

- task: PublishCodeCoverageResults@1  
  displayName: 'Publish code coverage'  
  inputs:  
    codeCoverageTool: Cobertura  
    summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml' 
```

**Comment by mlop3s** [comment]
Hi,

thanks for following up.
Here are some of the reports with the same issues.
https://github.com/microsoft/vstest/issues/2009
https://github.com/nunit/nunit3-vs-adapter/issues/519

Out projects are not .net core but .net Framework.
The solution we are building is a mix of C# and native C++

We do not use the yaml pipeline yet. This is our config:

```json
{
	"environment": {},
	"enabled": true,
	"continueOnError": false,
	"alwaysRun": false,
	"displayName": "Run Unit Tests",
	"timeoutInMinutes": 0,
	"condition": "succeeded()",
	"task": {
		"id": "ef087383-ee5e-42c7-9a53-ab56c98420f9",
		"versionSpec": "2.*",
		"definitionType": null
	},
	"inputs": {
		"testSelector": "testAssemblies",
		"testAssemblyVer2": "$(BuildConfiguration)\\**test*.dll\n!**\\*TestAdapter*.dll\n!**\\*TestPlatform*.dll\n!**\\obj\\**",
		"testPlan": "",
		"testSuite": "",
		"testConfiguration": "",
		"tcmTestRun": "$(test.RunId)",
		"searchFolder": "$(System.DefaultWorkingDirectory)",
		"testFiltercriteria": "\"TestCategory!=Integration&FullyQualifiedName!~Integration\"",
		"runOnlyImpactedTests": "false",
		"runAllTestsAfterXBuilds": "10",
		"uiTests": "false",
		"vstestLocationMethod": "version",
		"vsTestVersion": "toolsInstaller",
		"vstestLocation": "",
		"runSettingsFile": "",
		"overrideTestrunParameters": "",
		"pathtoCustomTestAdapters": "",
		"runInParallel": "false",
		"runTestsInIsolation": "true",
		"codeCoverageEnabled": "false",
		"otherConsoleOptions": "/Blame",
		"distributionBatchType": "basedOnTestCases",
		"batchingBasedOnAgentsOption": "autoBatchSize",
		"customBatchSizeValue": "10",
		"batchingBasedOnExecutionTimeOption": "autoBatchSize",
		"customRunTimePerBatchValue": "60",
		"dontDistribute": "False",
		"testRunTitle": "$(Build.DefinitionName) Unit Test Execution",
		"platform": "$(BuildPlatform)",
		"configuration": "$(BuildConfiguration)",
		"publishRunAttachments": "true",
		"diagnosticsEnabled": "true",
		"collectDumpOn": "onAbortOnly",
		"rerunFailedTests": "true",
		"rerunType": "basedOnTestFailurePercentage",
		"rerunFailedThreshold": "30",
		"rerunFailedTestCasesMaxLimit": "5",
		"rerunMaxAttempts": "1"
	}
}
```
Thanks,
Marco

**Comment by mlop3s** [comment]
Hi,

it looks like it's related to unity IOC. I've run peverify in unity.container.dll and I get some errors like:

```
[IL]: Error: [W:\MedicationGit\Debug\Unity.Container.dll : Unity.UnityContainer::ContextValidatingResolvePlan][offset 0x0000001E][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
```

Investigating further, but it sounds for me that excluding any dll that fails this test should solve the problem.

Cheers,
Marco

**Comment by OsirisTerje** [comment]
Interesting.  Awesome if you report back when you have identified the issue.

**Comment by mlop3s** [comment]
Hi,

that was it. I've changed the runsettings and now it works.
These are the steps to people having the same problem:

1. Identify which dll is causing the problem. Worst case, go one by one and run PEVerify.exe PathToThe.dll (tool is part of .net)
    => you will notice the faulting one, by a log like this:  [IL]: Error: [Unity.Container.dll .... 
2. Add the dll to the excluded ones in the runsettings like this (In my case it was unity IOC):

``` xml
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CodeCoverage>
            <ModulePaths>
              <Include>
                <ModulePath>.*.dll$</ModulePath>
                <ModulePath>.*.exe$</ModulePath>
              </Include>
              <Exclude>
                <ModulePath>.*CPPUnitTestFramework.*</ModulePath>
                <ModulePath>.*nunit.*</ModulePath>
                <ModulePath>.*mock.*</ModulePath>
                <ModulePath>.*toolkit.*</ModulePath>
                <ModulePath>.*microsoft.*</ModulePath>
                <ModulePath>.*unity.*</ModulePath>
                <ModulePath>.*system.*</ModulePath>
              </Exclude>
            </ModulePaths>
```` 

That's all. Error is gone.
I will close the ticket.

Cheers,
Marco

**Comment by OsirisTerje** [comment]
Thanks for the solution :-)
