### ISSUE TITLE
Duplicated message when in TearDown when Assert.Fail is called.

### ISSUE THREAD

**Issue by TsvetanIlchev** [nunit/nunit3-vs-adapter#871]
Since NUnit3TestAdapter version 3.14, if you start some test and you have Assert.Fail in the TearDown of the test class, the message is shown twice.
On NUnit3TestAdapter version 3.13, the issue is not observed.
Also if you call Assert.Fail, into the test, not in the TearDown part.
```Example
    [TestFixture]
    public class Tests
    {
        bool b1 = true;
        bool b2 = false;

        [Test]
        public void NUnitTest()
        {
            b1 = true;
            b2 = false;
        }

        [TearDown]
        public void TearDownTest()
        {
            if (b1 != b2)
            {
                Assert.Fail("Test failed!");
            }
        }
    }
```
```
  Message: 
    Test failed!
    TearDown : NUnit.Framework.AssertionException : Test failed!
```
As you can see Test failed! is printed twice.

Used versions:
"nunit" Version="3.13.2"
"NUnit3TestAdapter" Version="4.0.0"

**Comment by OsirisTerje** [comment]
Looks like this comes from the NUnit.Engine (or even the framework itself.  The input to the adapter from the engine is:
```xml
<test-case id='0-1001' name='NUnitTest' fullname='Issue871.Tests.NUnitTest' methodname='NUnitTest' classname='Issue871.Tests' runstate='Runnable' seed='985735954' result='Failed' label='Error' start-time='2021-10-06 11:26:59Z' end-time='2021-10-06 11:26:59Z' duration='0.028825' asserts='0' parentId='0-1000'>
   <failure>
      <message><![CDATA[Test failed!
TearDown : NUnit.Framework.AssertionException : Test failed!]]></message>
      <stack-trace><![CDATA[   at Issue871.Tests.TearDownTest() in C:\repos\NUnit\nunit3-vs-adapter.issues\Issue871\UnitTest1.cs:line 23

--TearDown
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail(String message)
   at Issue871.Tests.TearDownTest() in C:\repos\NUnit\nunit3-vs-adapter.issues\Issue871\UnitTest1.cs:line 23]]></stack-trace>
   </failure>
   <assertions>
      <assertion result='Failed'>
         <message><![CDATA[Test failed!]]></message>
         <stack-trace><![CDATA[   at Issue871.Tests.TearDownTest() in C:\repos\NUnit\nunit3-vs-adapter.issues\Issue871\UnitTest1.cs:line 23
]]></stack-trace>
      </assertion>
   </assertions>
</test-case>
```
As can be seen the failure/message contains both lines.  The different adapters may use different versions of the engine, so it is probably this one that causes this. 

@ChrisMaddock Can you check this?  And also if this issue should be moved over to the engine repo?
