### ISSUE TITLE
Couldn't Install test adapter in VS2022 Preview Enterprise 

### ISSUE THREAD

**Issue by bullmastiffo** [nunit/nunit3-vs-adapter#872]
I have
Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 1.1

I've downloaded NUnit3TestAdapter-4.0.0 when I try to install it says no suitable version
![image](https://user-images.githubusercontent.com/11883159/124302293-4d4af200-db61-11eb-9c93-a0fed79bcdb5.png)

here's the log below.

Am I doing something wrong? 🤔

```
07/02/2021 18:13:46 - Microsoft VSIX Installer
07/02/2021 18:13:46 - -------------------------------------------
07/02/2021 18:13:46 - vsixinstaller.exe version:
07/02/2021 18:13:46 - 17.0.1616-preview1
07/02/2021 18:13:46 - -------------------------------------------
07/02/2021 18:13:46 - Command line parameters:
07/02/2021 18:13:46 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\mavic\Downloads\NUnit3TestAdapter-4.0.0.vsix
07/02/2021 18:13:46 - -------------------------------------------
07/02/2021 18:13:46 - Microsoft VSIX Installer
07/02/2021 18:13:46 - -------------------------------------------
07/02/2021 18:13:47 - Initializing Install...
07/02/2021 18:13:47 - Extension Details...
07/02/2021 18:13:47 - 	Identifier         : NUnit.NUnit3TestAdapter
07/02/2021 18:13:47 - 	Name               : NUnit 3 Test Adapter
07/02/2021 18:13:47 - 	Author             : Charlie Poole, Terje Sandstrom
07/02/2021 18:13:47 - 	Version            : 4.0.0
07/02/2021 18:13:47 - 	Description        : NUnit 3 adapter for running tests in Visual Studio. Works with NUnit 3.x and higher.
Note that use of VSIX Test adapters are deprecated in VS 2019 and later, we recommend you to use the nuget versions of the adapter. 
(For running NUnit 2 tests, use the NUnit 2 adapter.)
07/02/2021 18:13:47 - 	Locale             : en-US
07/02/2021 18:13:47 - 	MoreInfoURL        : https://docs.nunit.org/articles/vs-test-adapter/Index.html
07/02/2021 18:13:47 - 	InstalledByMSI     : False
07/02/2021 18:13:47 - 	SupportedFrameworkVersionRange : [4.5,)
07/02/2021 18:13:47 - 
07/02/2021 18:13:47 - 	SignatureState     : Unsigned
07/02/2021 18:13:47 - 	Supported Products : 
07/02/2021 18:13:47 - 		Microsoft.VisualStudio.Community
07/02/2021 18:13:47 - 			Version : [11.0,18.0)
07/02/2021 18:13:47 - 			ProductArchitecture : notSpecified
07/02/2021 18:13:47 - 		Microsoft.VisualStudio.Pro
07/02/2021 18:13:47 - 			Version : [11.0,18.0)
07/02/2021 18:13:47 - 			ProductArchitecture : notSpecified
07/02/2021 18:13:47 - 		Microsoft.VisualStudio.Enterprise
07/02/2021 18:13:47 - 			Version : [11.0,18.0)
07/02/2021 18:13:47 - 			ProductArchitecture : notSpecified
07/02/2021 18:13:47 - 
07/02/2021 18:13:47 - 	References         : 
07/02/2021 18:13:47 - 	Prerequisites      : 
07/02/2021 18:13:47 - 		-------------------------------------------------------
07/02/2021 18:13:47 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
07/02/2021 18:13:47 - 		Name         : Visual Studio core editor
07/02/2021 18:13:47 - 		Version      : [15.0.25904.1,)
07/02/2021 18:13:47 - 
07/02/2021 18:13:47 - 		-------------------------------------------------------
07/02/2021 18:13:47 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
07/02/2021 18:13:47 - 		Name         : .NET desktop development tools
07/02/2021 18:13:47 - 		Version      : [15.0.25904.0,)
07/02/2021 18:13:47 - 
07/02/2021 18:13:47 - Signature Details...
07/02/2021 18:13:47 - 	Extension is not signed.
07/02/2021 18:13:47 - 
07/02/2021 18:13:47 - Searching for applicable products...
07/02/2021 18:13:47 - Found installed product - Global Location
07/02/2021 18:13:47 - Found installed product - Visual Studio Enterprise 2022 Preview
07/02/2021 18:13:47 - Found installed product - Visual Studio Enterprise 2019
07/02/2021 18:13:47 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by OsirisTerje** [comment]
Thanks for verifying that the Vsix actually doesn't work with VS2022.  You should use the nuget adapter version.  

I have removed the vsix from the release (it was actually added there by mistake), and there is no 4.0.0 update either on the visuals studio marketplace.  

Using the nuget adapter is easier and the recommended way going forward.  Add it to each test project in your solution.  

About the vsix:  We may be able to make a 4.0 version some time later, but currently we don't know the requirements from VS2022 wrt this.
