### ISSUE TITLE
Cannot run tests where test name gets changed by code. Test run is just skipped

### ISSUE THREAD

**Issue by informatorius** [nunit/nunit3-vs-adapter#881]
Cannot run tests where test name gets changed by code. Test run is just skipped
[TestProject1.zip](https://github.com/nunit/nunit3-vs-adapter/files/7067808/TestProject1.zip)

Test name is changed with nunit SetName method to add parameter values to the test name then shown in test explorer.

* NUnit and NUnit3TestAdapter versions: nunit 3.10 and adapter 3.17
* Visual Studio edition and full version number (see Help About): Microsoft Visual Studio Enterprise 2019
Version 16.11.2
* A short repro, preferably attached or pointing to a git repo or gist: Attached
* What .net platform and version is being targeted. Windows 10 dotnet 4.8

![image](https://user-images.githubusercontent.com/6989214/131146310-40e583c1-325f-49e2-92de-d853cb9f840b.png)

NUnit Adapter 3.17.0.0: Test execution started
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Invalid Condition 'FullyQualifiedName=TestProject1.Tests.Test1:input1=False'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryContext.GetTestCaseFilter(IEnumerable`1 supportedProperties, Func`2 propertyProvider)
   at NUnit.VisualStudio.TestAdapter.TfsTestFilter.get_TfsTestCaseFilterExpression() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TfsTestFilter.cs:line 96
   at NUnit.VisualStudio.TestAdapter.TfsTestFilter.get_IsEmpty() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TfsTestFilter.cs:line 99
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.InitializeForExecution(IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 205
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 94
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 134,2 ms ==========

**Comment by OsirisTerje** [comment]
1. Ensure you have the latest packages 
```
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0"/>
  </ItemGroup>
```

2. The test run should run and show this:
![image](https://user-images.githubusercontent.com/203432/131245101-d8975e9b-6212-40a3-8a88-ed1017e97200.png)

3. The  non-run Test1 test is a result of having the RTD turned on, It doesn't harm anything, but if it is too annoying, you can turn off RTD
![image](https://user-images.githubusercontent.com/203432/131245143-2a6dabdf-ba3c-4a7c-9d82-e279f11c98df.png)
and the result is now
![image](https://user-images.githubusercontent.com/203432/131245164-9b7f985b-56a8-4d05-bf04-316d8bb543bd.png)

Fixing the non-.run Test1 in Test Explorer depends on MS fixing the RTD, @kendrahavens.  



Note:
Now, I managed to make this work using either net5.0 or net6.0.  When using net4.8 I got an error, which seems unrelated,  which I have reported, and which also can be seen here:  https://stackoverflow.com/questions/58419189/error-streamjsonrpc-connectionlostexception-the-json-rpc-connection-with-the-r 

Note 2:  The repro is uploaded here:   https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue881/TestProject1
