### ISSUE TITLE
 Skipping the import of Visual Studio XML code coverage for the invalid file path: D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter

### ISSUE THREAD

**Issue by netmajor** [nunit/nunit3-vs-adapter#882]
When reporting a bug, please provide the following information to speed up triage:

* NUnit 3.13.1 and NUnit3TestAdapter 3.17
* Visual Studio 16.10.2
* .net core 3.1
* TeamCity Enterprise 2020.1.3

When I run in TeamCity sonar end step:
```
$sonarToken = "%SonarProjectToken%";

Write-Host "CodeCoverage processing...";
$dir = get-location
write-host $dir

Get-ChildItem -Recurse -Filter "*.coverage" | Foreach-Object {    
    $outfile = "$([System.IO.Path]::GetFileNameWithoutExtension($_.FullName)).coveragexml"
    $output = [System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName($_.FullName), $outfile)
    write-host $outfile
    write-host $output
    &C:\microsoft.codecoverage.16.8.3\build\netstandard1.0\CodeCoverage\CodeCoverage.exe analyze /output:$output $_.FullName 
}  
Write-Host "CodeCoverage finished";

&c:\sonarscanner\dotnet-sonarscanner.exe end /d:sonar.login=$sonarToken | Out-Host;
```

in console i got multiple warnings:
  WARN: Skipping the import of Visual Studio XML code coverage for the invalid file path: D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\AdapterSettings.cs at line 12518
  WARN: Skipping the import of Visual Studio XML code coverage for the invalid file path: D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\Metadata\TypeInfo.cs at line 12520
  WARN: Skipping the import of Visual Studio XML code coverage for the invalid file path: D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs at line 12522

with callstack:

java.io.IOException: The device is not ready
19:27:49
    at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
19:27:49
    at java.base/java.io.WinNTFileSystem.canonicalize(Unknown Source)
19:27:49
    at java.base/java.io.File.getCanonicalPath(Unknown Source)
19:27:49
    at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser$Parser.handleSourceFileTag(VisualStudioCoverageXmlReportParser.java:109)
19:27:49
    at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser$Parser.dispatchTags(VisualStudioCoverageXmlReportParser.java:76)
19:27:49
    at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser$Parser.parse(VisualStudioCoverageXmlReportParser.java:62)
19:27:49
    at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser.accept(VisualStudioCoverageXmlReportParser.java:44)
19:27:49
    at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser.accept(VisualStudioCoverageXmlReportParser.java:32)
19:27:49
    at org.sonar.plugins.dotnet.tests.CoverageCache.readCoverageFromCacheOrParse(CoverageCache.java:39)
19:27:49
    at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(CoverageAggregator.java:135)
19:27:49
    at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(CoverageAggregator.java:120)
19:27:49
    at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.analyze(CoverageReportImportSensor.java:86)
19:27:49
    at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.execute(CoverageReportImportSensor.java:82)
19:27:49
    at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
19:27:49
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
19:27:49
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:62)
19:27:49
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
19:27:49
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
19:27:49
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
19:27:49
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
19:27:49
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
19:27:49
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
19:27:49
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
19:27:49
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
19:27:49
    at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
19:27:49
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
19:27:49
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
19:27:49
    at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
19:27:49
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
19:27:49
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
19:27:49
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:27:49
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

**Comment by OsirisTerje** [comment]
Obviously an error in the Sonar system, but then, it should not even try to analyze the NUnitAdapter, so I suggest you add excludes for that in your runsettings.

**Comment by netmajor** [comment]
I have moved to coverlet as code coverage tool and it works ;)

**Comment by OsirisTerje** [comment]
Awesome!
