### ISSUE TITLE
NUnit3TestAdapter 4.0.0 - DiscoveryException: Not a TestFixture, SetUpFixture or TestSuite, but ParameterizedFixture

### ISSUE THREAD

**Issue by thomhurst** [nunit/nunit3-vs-adapter#884]
I have a pipeline in TeamCity, and I recently upgraded the NUnit3TestAdapter package from 3.17.0 to 4.0.0

I noticed that the pipeline didn't fail, but TeamCity didn't show my tests as having being run.

I looked into the build log and can see this exception:

```
	[dotnet test] Exception NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryException,    Exception thrown executing tests in C:\BuildAgent\work\bdda9fcf3e0e8340\test\AcceptanceTests\bin\Debug\netcoreapp3.1\AcceptanceTests.dll
[15:11:35]	[dotnet test] Not a TestFixture, SetUpFixture or TestSuite, but ParameterizedFixture
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractTestFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 252
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 223
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ConvertXml(NUnitResults discovery) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 180
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.Convert(NUnitResults discoveryResults, String assemblyPath) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 134
[15:11:35]	[dotnet test]    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 280
[15:11:35]	[dotnet test] NUnit Adapter 4.0.0.0: Test execution complete
[15:11:35]	[dotnet test] No test is available in C:\BuildAgent\work\bdda9fcf3e0e8340\test\AcceptanceTests\bin\Debug\netcoreapp3.1\AcceptanceTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

Tests are being run on .NET Core 3.1

**Comment by mikkelbu** [comment]
I've transferred the issue to the adapter project. This sounds related to https://github.com/nunit/nunit3-vs-adapter/discussions/867

**Comment by OsirisTerje** [comment]
Yes, except we lack a repro, perhaps @thomhurst can provide a small repro ?

**Comment by thomhurst** [comment]
@OsirisTerje Clone this repo and run the powershell script (or run `dotnet test` from the same directory as the solution)

[https://github.com/thomhurst/NUnitTestAdapterIssueRepro](https://github.com/thomhurst/NUnitTestAdapterIssueRepro)

**Comment by OsirisTerje** [comment]
Thanks @thomhurst !  

I've added the discovery xml from your repro to a unit test (ThatSetUpFixtureWorksIssue884) in the project, and it confirmed the issue!  I've also added a fix for this.  

I thought this case was covered but turned out the XML  was slightly off, so this triggered. 

Using the fixed adapter, it also works on your repro:
![image](https://user-images.githubusercontent.com/203432/134427191-bdd02e24-9c68-4875-9eb7-3641144ad287.png)

 An alpha01 package is attached to this comment.  Very nice if you could verify on your system too.

Thanks for reporting this, and providing the repro!
[NUnit3TestAdapter.4.1.0-alpha01.zip](https://github.com/nunit/nunit3-vs-adapter/files/7214073/NUnit3TestAdapter.4.1.0-alpha01.zip)

**Comment by thomhurst** [comment]
@OsirisTerje brilliant, that works for me! Glad I could help :)
![image](https://user-images.githubusercontent.com/30480171/134429040-d45161cb-36df-4f3e-8e87-1d13c91dc238.png)
