### ISSUE TITLE
With NUnit3TestAdapter 4.1.0 and 4.0.0, the NUnitFixtureOrdering does not work.

### ISSUE THREAD

**Issue by PatrickLeGarrec** [nunit/nunit3-vs-adapter#923]
With NUnit3TestAdapter 4.1.0 and 4.0.0, the NUnitFixtureOrdering does not work.

========== Starting test run ==========
NUnit Adapter 4.1.0.0: Test execution started
Running selected tests in C:\Demo\Fixtures\Fixtures\bin\Debug\net6.0-windows\Fixtures.dll
Exception NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryException,    Exception thrown executing tests in C:\Demo\Fixtures\Fixtures\bin\Debug\net6.0-windows\Fixtures.dll
Expected ParameterizedMethod, Theory or GenericMethod, but was TestFixture
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractParameterizedMethodsAndTheories(NUnitDiscoveryTestFixture tf, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 299
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 214
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractTestFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 267
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 229
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ConvertXml(NUnitResults discovery) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 185
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.Convert(NUnitResults discoveryResults, String assemblyPath) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 137
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 279
NUnit Adapter 4.1.0.0: Test execution complete
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 154 ms ==========

![image](https://user-images.githubusercontent.com/89050431/143871621-bd9b4f9c-376c-4351-9c0b-901bd13d3257.png)

![image](https://user-images.githubusercontent.com/89050431/143872455-7d741e09-9555-446f-ba0d-6846ab14ce3a.png)

It is very annoying because this library is SO great and used by all our functional tests.

repos :

https://github.com/PatrickLeGarrec/NUnitFixtureOrdering

Note that it works with test adapter 3.17

**Comment by OsirisTerje** [comment]
Thanks!  If you add a runsetting option setting the DiscoveryMode to Legacy, does it work then?

**Comment by PatrickLeGarrec** [comment]
KO  with legacy mode :(

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <RunConfiguration>
        <MaxCpuCount>0</MaxCpuCount>
    </RunConfiguration>
    <NUnit>
        <Verbosity>5</Verbosity>
        <DumpXmlTestResults>true</DumpXmlTestResults>
        <DumpXmlTestDiscovery>true</DumpXmlTestDiscovery>
        <DiscoveryMethod>Legacy</DiscoveryMethod>
    </NUnit>
</RunSettings>

**Comment by OsirisTerje** [comment]
Ok, that is strange, because legacy should be equal to 3.17, it is in fact the same code.   Weird....  But I'll check your repro :-)

**Comment by OsirisTerje** [comment]
The NUnitOrdering library is included as a source project, so it also interferes with the visual studio testhost, so it tries to start that one also.  It doesn't work with either 4.1, any of the alphas of 4.2 or 3.17.  And, it utterly confuses the Real TIme Test discovery of Visual Studio.   
I had a few times where it sort of ran, but then there is an exception inside some trait it adds. 
![image](https://user-images.githubusercontent.com/203432/144313595-78cd4eb3-1fb2-4f18-8ec7-d81c66d29106.png)

The error message on the Fixtures assembly, says it fails in the internal engine adapter inside the test3adapter, and it cant make sense of the type of fixture that's here.  
![image](https://user-images.githubusercontent.com/203432/144313794-30b2ef1a-8881-46b8-9b40-d98c9eaf0b25.png)

This is not unexpected, since it introduces a new type of fixture, and there is no object model for that to deserialize the message into.  The current discovery mode uses a strongly typed object model. Now, the Legacy discovery mode should be able to handle this, but it fails too, not even sure why that is.  And 3.17 fails too, so....  It might work with the nuget package though, I haven't tried that.  And I assume you use the source to be able to use Net6. 

The library has very few downloads, and it doesn't look like it is being maintained.  If it should work with the 4.X series, it would need to also add a strongly typed parser and inject that into the fixture parsing in the adapter. Over time it could be interesting to open up that for extensions, but currently, it is not.  You could fork the adapter code of course and add it in your own variant though.

**Comment by Sebazzz** [comment]
Author of ]NUnitTestOrdering](https://github.com/Sebazzz/NUnitTestOrdering) chiming in - I suspect, as you say, this is unfixable without also forking the test adapter. It is what it is.

**Comment by OsirisTerje** [comment]
Thanks @Sebazzz .   It is possible to add that injection point into the adapter, and if you or @PatrickLeGarrec or anyone really would like to do that, we would be happy to include that!

**Comment by PatrickLeGarrec** [comment]
Hi guys ^^  It would be very great to add this. 
NUnit Ordering lib is important for me because we use it in our company.
