### ISSUE TITLE
Unable to cast transparent proxy to type System.Web.UI.ICallbackEventHandler

### ISSUE THREAD

**Issue by CCUng** [nunit/nunit3-vs-adapter#973]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
NUnit 3.12.0 and 3.17.0
NUnit3TestAdapter 4.2.1

* Visual Studio edition and full version number (see Help About)
Azure devops, 16.11.0 and 17.1 - both same exception

* A short repro, preferably attached or pointing to a git repo or gist
We tried to reproduce locally but it only appears to occur on Azure devops.

* What .net platform and version is being targeted
net6.0

* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in
Azude devops, MS-hosted CI_agent, task VSTest@2

We try to upgrade from Nunit3TestAdapter 3.17.0 to 4.2.1, in our build pipeline in Azure devops. Discovering tests for net6.0 throws exception:

```
Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in xxx\bin\Debug\net6.0\xxx.test.dll
The NUnit 3 driver encountered an error while executing reflected code.
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 89
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 279
InnerException: System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
```

**Comment by OsirisTerje** [comment]
You say you update the adapter in your build pipeline?  Does that mean you don't have it as a nuget package in your test project ?
If you have it as a nuget package, what happens when you run the tests from the command line?  (aka `dotnet test`)

**Comment by CCUng** [comment]
Hi Terje, 

Thank you for replying.

Currently we have in our test project (```<TargetFrameworks>net48;net6.0</TargetFrameworks>```) NUnit3TestAdapter, 3.17.0

As in:
```
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
```

This runs just well, locally and in Azure DevOps.

We want to upgrade to 4.2.1, as in:

```
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
```

This works fine locally, but not in Azure DevOps.

The output when running the test locally is:

```
c:\code\project\test\Project.Test>dotnet test -l "console;verbosity=detailed"
  Determining projects to restore...
  All projects are up-to-date for restore.
  Project1 -> c:\code\project\src\Project1\bin\Debug\netstandard2.0\Project1.dll
  Project2 -> c:\code\project\src\Project2\bin\Debug\netstandard2.0\Project2.dll
  Project.Test -> c:\code\project\test\Project.Test\bin\Debug\net48\Project.Test.dll
  Project.Test -> c:\code\project\test\Project.Test\bin\Debug\net6.0\Project.Test.dll
Test run for c:\code\project\test\Project.Test\bin\Debug\net48\Project.Test.dll (.NETFramework,Version=v4.8)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
c:\code\project\test\Project.Test\bin\Debug\net48\Project.Test.dll
NUnit Adapter 4.2.0.0: Test execution started
Running all tests in c:\code\project\test\Project.Test\bin\Debug\net48\Project.Test.dll
   NUnit3TestExecutor discovered 8 of 8 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.2.0.0: Test execution complete
  Passed Test1 [29 ms]
  Passed Test2 [< 1 ms]
  Passed Test3 [< 1 ms]
  Passed Test4 [314 ms]
  Passed Test5 [1 ms]
  Passed Test6 [1 ms]
  Passed Test7 [1 ms]
  Passed Test8 [1 ms]

Test Run Successful.
Total tests: 8
     Passed: 8
 Total time: 1.4565 Seconds
Test run for c:\code\project\test\Project.Test\bin\Debug\net6.0\Project.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
c:\code\project\test\Project.Test\bin\Debug\net6.0\Project.Test.dll
NUnit Adapter 4.2.0.0: Test execution started
Running all tests in c:\code\project\test\Project.Test\bin\Debug\net6.0\Project.Test.dll
   NUnit3TestExecutor discovered 8 of 8 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.2.0.0: Test execution complete
  Passed Test1 [17 ms]
  Passed Test2 [< 1 ms]
  Passed Test3 [< 1 ms]
  Passed Test4 [123 ms]
  Passed Test5 [1 ms]
  Passed Test6 [< 1 ms]
  Passed Test7 [1 ms]
  Passed Test8 [< 1 ms]

Test Run Successful.
Total tests: 8
     Passed: 8
 Total time: 1.0224 Seconds
```

**Comment by OsirisTerje** [comment]
I created a new nunit project, and added both frameworks.  It builds with no problems in Azure DevOps, so there must be something else in your project that triggers this behavior.  
From the error message it looks like you do something with the Web.Ui.
1.  Can you create a small repro for this?
2. Do you have the same issue with the latest NUnit Framework?

**Comment by CCUng** [comment]
Hello Terje. Sorry about the delay.

I have prepared a repo as you requested: 

https://github.com/CCUng/nunit3testadapter-sample

With this, azure fails to build:


```
NUnit Adapter 4.2.0.0: Test execution started
Running all tests in D:\a\1\s\Lib.Test\bin\Debug\net6.0\testcentric.engine.metadata.dll
Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in D:\a\1\s\Lib.Test\bin\Debug\net6.0\testcentric.engine.metadata.dll
Unsupported Target Framework: .NETStandard,Version=v2.0
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFrameworkInner(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.GetEngineRunner()
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 89
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 279
NUnit Adapter 4.2.0.0: Test execution complete
No test is available in D:\a\1\s\Lib.Test\bin\Debug\net6.0\testcentric.engine.metadata.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in D:\a\1\s\Lib.Test\bin\Debug\net6.0\Lib.Test.dll
The NUnit 3 driver encountered an error while executing reflected code.
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 89
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 279
InnerException: System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
NUnit Adapter 4.2.0.0: Test execution complete
No test is available in D:\a\1\s\Lib.Test\bin\Debug\net6
```

Thank you!

**Comment by OsirisTerje** [comment]
The error message says the engine reads the framework for the test assembly as netstandard.  That is wrong, but this is sent down from the vstest task.   Your sample works fine with dotnet test, so the error must be in the build yml file.    From the definition of the task, I can't see that it actually runs the net4.8 assembly (ref l 57)
That said, the vstest task has always been a bit troublesome, so the best route is to use `dotnet test`, also in the yml file.

**Comment by Bouke** [comment]
Hi @OsirisTerje, I'm a colleague of @CCUng. Thank you for your investigation, it helped us diagnose the problem. After carefully going through the output of VSTest we found the issue:

> Test run detected DLL(s) which were built for different framework and platform versions. Following DLL(s) do not match current settings, which are .NETFramework,Version=v4.0 framework and X86 platform.
> testcentric.engine.metadata.dll is built for Framework .NETStandard,Version=v2.0 and Platform AnyCPU.

After excluding this assembly from test assembly discovery the .NET 6 tests run fine. 👍

**Comment by OsirisTerje** [comment]
@Bouke @CCUng  Awesome!  Thanks for reporting back!
