### ISSUE TITLE
#817 still problematic

### ISSUE THREAD

**Issue by Amleto** [nunit/nunit3-vs-adapter#977]
See https://github.com/nunit/nunit3-vs-adapter/issues/817 for steps. I see the same issue with

- NUnit adapter 3.11.2.0
- Microsoft Test Execution Command Line Tool Version 17.2.0-preview-20220401-08

This is a net fx 4.8 project.

```
NUnit Adapter 3.11.2.0: Test execution started
##[error]An exception occurred while invoking executor 'executor://nunit3testexecutor/': Filter string '2\,2.944379d\,1.4609d' includes unrecognized escape sequence.
##[error]Stack trace:
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscoveryContext.GetTestCaseFilter(IEnumerable`1 supportedProperties, Func`2 propertyProvider)
##[error]   at NUnit.VisualStudio.TestAdapter.TfsTestFilter.get_TfsTestCaseFilterExpression()
##[error]   at NUnit.VisualStudio.TestAdapter.TfsTestFilter.get_IsEmpty()
##[error]   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.Initialize(IRunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass47_0.<RunTestInternalWithExecutors>b__0()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
##[error]--- End of stack trace from previous location where exception was thrown ---
##[error]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

```

**Comment by Amleto** [comment]
I don't have access to the agents to modify that.

**Comment by OsirisTerje** [comment]
You should not need that.  The adapter should be added as a nuget package to your test projects.  The VSix versions are deprecated, and newer VS versions don't really support them anymore.

**Comment by Amleto** [comment]
Hi, after some further research I think the problem is in the azure vstest task, rather than some nunintadapter/vstest direct interaction. Going to post on azure pipelines
